#!/bin/sh

# todo(ibolmo): Allow // # or drop the prefix (for multiline comments)
# todo(ibolmo): Use $USER or argument for the user
# todo(ibolmo): Pass argument to narrow search

grep -RiP '#[ \t]*todo.*olmo' *

